/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.AviaoDAO;
import DAO.VooDAO;
import DAO.Voo_Aviao_DAO;
import Javabeans.Aviao;
import Javabeans.Aviao_Voo;
import Javabeans.Voo;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author h11hu
 */
public class CRUD_VOO extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_VOO
     */
    public void preenchetabela() {

        VooDAO dao = new VooDAO();
        List<Voo> voos = dao.listarVoos();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        for (Voo v : voos) {
            modelo.addRow(new Object[]{
                v.getId_voo(),
                v.getDestino(),
                v.getPrefixo_aeronautico(),
                v.getItinerario(),
                v.getDia(),
                v.getHorario(),
                v.getTripulacao()});
        }
    }

    public CRUD_VOO() {
        initComponents();

        //preenche o combobox de avioes
        AviaoDAO dao = new AviaoDAO();
        for (String a : dao.read()) {
            boxaviao.addItem(a);
        }
        //preenche o combobox de avioes

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btsalvar = new javax.swing.JButton();
        btvoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxaviao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cxhorario = new javax.swing.JTextField();
        cxdestino = new javax.swing.JTextField();
        cxdia = new javax.swing.JTextField();
        cxitinerario = new javax.swing.JTextField();
        cxtripulacao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        bteditar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        btpesquisa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelagb = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btexcluir2 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btvoltar.setText("Voltar");
        btvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Forneça as informações do voo");

        jLabel2.setText("Horário");

        jLabel3.setText("Destino");

        jLabel4.setText("Avião");

        boxaviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxaviaoActionPerformed(evt);
            }
        });

        jLabel5.setText("Dia");

        jLabel6.setText("Itinerário");

        jLabel7.setText("Tripulação");

        cxhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxhorarioActionPerformed(evt);
            }
        });

        cxitinerario.setText("1");
        cxitinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxitinerarioActionPerformed(evt);
            }
        });

        cxtripulacao.setText("3");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Destino", "Aviao", "Itinerario", "Dia", "Horario", "Tripulacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        bteditar.setText("Editar");
        bteditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditarActionPerformed(evt);
            }
        });

        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Destino", "Aviao", "Itinerario", "Dia", "Horario", "Tripulacao", "modelo", "idade", "assentos", "capacidade_tanque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela1);

        btpesquisa.setText("Pesquisar");
        btpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisaActionPerformed(evt);
            }
        });

        jButton2.setText("Agrupamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelagb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contagem", "Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelagb);

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btexcluir2.setText("Excluir");
        btexcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btsalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bteditar)
                                .addGap(18, 18, 18)
                                .addComponent(btexcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btvoltar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(118, 118, 118)
                                    .addComponent(jLabel1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(cxhorario, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxitinerario))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cxtripulacao))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cxdestino)
                                        .addComponent(cxdia)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(boxaviao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(79, 79, 79))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btpesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(btexcluir2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cxhorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cxdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(boxaviao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cxdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cxitinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cxtripulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(btvoltar)
                    .addComponent(bteditar)
                    .addComponent(btexcluir)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btpesquisa)
                    .addComponent(jButton1)
                    .addComponent(btexcluir2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        try {
            Voo voo = new Voo();

            voo.setHorario(cxhorario.getText());
            voo.setDestino(cxdestino.getText());
            voo.setPrefixo_aeronautico((String) boxaviao.getSelectedItem());
            voo.setDia(cxdia.getText());
            voo.setItinerario(Integer.parseInt(cxitinerario.getText()));
            voo.setTripulacao(Integer.parseInt(cxtripulacao.getText()));
            VooDAO dao = new VooDAO();
            dao.cadastrarVoo(voo);
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO " + e);
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void cxhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxhorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxhorarioActionPerformed

    private void boxaviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxaviaoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_boxaviaoActionPerformed

    private void btvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoltarActionPerformed
        // TODO add your handling code here:
        final TELA_ADM exibir = new TELA_ADM();
        this.dispose();
        exibir.setVisible(true);


    }//GEN-LAST:event_btvoltarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        preenchetabela();

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        preenchetabela();

    }//GEN-LAST:event_formWindowOpened

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked

        cxhorario.setText((String) tabela.getValueAt(tabela.getSelectedRow(), 5));
        cxdia.setText((String) tabela.getValueAt(tabela.getSelectedRow(), 4));
        cxdestino.setText((String) tabela.getValueAt(tabela.getSelectedRow(), 1));
        cxitinerario.setText(Integer.toString((int) tabela.getValueAt(tabela.getSelectedRow(), 3)));
        cxtripulacao.setText(Integer.toString((int) tabela.getValueAt(tabela.getSelectedRow(), 6)));

    }//GEN-LAST:event_tabelaMouseClicked

    private void bteditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditarActionPerformed
        // TODO add your handling code here:
        try {
            Voo voo = new Voo();

            //CONVERTER STRING PARA TIME (HORA)
            /*String str = cxhorario.getText();
            SimpleDateFormat formatador = new SimpleDateFormat("HH:mm"); 
            java.sql.Date data = (java.sql.Date) formatador.parse(str); 
            java.sql.Time time = new java.sql.Time(data.getTime());*/
            //CONVERTER STRING PARA TIME (HORA)
            //CONVERTER STRING PARA DATE (DATA)
            /*DateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");
            java.sql.Date dia = (java.sql.Date)formatter.parse(cxdia.getText());*/
            //CONVERTER STRING PARA DATE (DATA)
            //voo.setHorario(time);
            voo.setDestino(cxdestino.getText());
            voo.setPrefixo_aeronautico((String) boxaviao.getSelectedItem());
            voo.setHorario(cxhorario.getText());
            voo.setDia(cxdia.getText());

            //voo.setDia(cxdia.getText());
            voo.setItinerario(Integer.parseInt(cxitinerario.getText()));
            voo.setTripulacao(Integer.parseInt(cxtripulacao.getText()));
            voo.setId_voo((int) tabela.getValueAt(tabela.getSelectedRow(), 0));
            VooDAO dao = new VooDAO();
            dao.editarVoo(voo);
            JOptionPane.showMessageDialog(null, "Edicao realizado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO " + e);
        }

    }//GEN-LAST:event_bteditarActionPerformed

    private void cxitinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxitinerarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxitinerarioActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        // TODO add your handling code here:
        try {
            VooDAO dao = new VooDAO();
            dao.excluirVoo((int) tabela.getValueAt(tabela.getSelectedRow(), 0));
            JOptionPane.showMessageDialog(null, "Exclusao realizado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO " + e);
        }
    }//GEN-LAST:event_btexcluirActionPerformed

    private void tabela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabela1MouseClicked

    private void btpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisaActionPerformed
        // TODO add your handling code here:
        try {
            Voo_Aviao_DAO dao = new Voo_Aviao_DAO();
            List<Aviao_Voo> voos = dao.listarVoos((String) boxaviao.getSelectedItem());
            DefaultTableModel modelo = (DefaultTableModel) tabela1.getModel();
            modelo.setNumRows(0);
            for (Aviao_Voo v : voos) {
                modelo.addRow(new Object[]{
                    v.getId_voo(),
                    v.getDestino(),
                    v.getPrefixo_aeronautico(),
                    v.getItinerario(),
                    v.getDia(),
                    v.getHorario(),
                    v.getTripulacao(),
                    v.getModelo(),
                    v.getIdade(),
                    v.getAssentos(),
                    v.getCapacidade_tanque()

                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO " + e);
        }

    }//GEN-LAST:event_btpesquisaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            VooDAO dao = new VooDAO();
            List<Voo> voos = dao.gbVoos();
            DefaultTableModel modelo = (DefaultTableModel) tabelagb.getModel();
            modelo.setNumRows(0);
            for (Voo v : voos) {
                modelo.addRow(new Object[]{
                    v.getCount(),
                    v.getDestino()});
            }
            JOptionPane.showMessageDialog(null, "Pesquisa realizada com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO " + e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tabela1.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btexcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluir2ActionPerformed
        // TODO add your handling code here:
        try {
            VooDAO dao = new VooDAO();
            dao.excluirVoo((String) tabela1.getValueAt(tabela1.getSelectedRow(), 2));
            JOptionPane.showMessageDialog(null, "Exclusao realizado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO " + e);
        }
    }//GEN-LAST:event_btexcluir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_VOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_VOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_VOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_VOO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_VOO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> boxaviao;
    private javax.swing.JButton bteditar;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btexcluir2;
    private javax.swing.JButton btpesquisa;
    private javax.swing.JButton btsalvar;
    private javax.swing.JButton btvoltar;
    private javax.swing.JTextField cxdestino;
    private javax.swing.JTextField cxdia;
    private javax.swing.JTextField cxhorario;
    private javax.swing.JTextField cxitinerario;
    private javax.swing.JTextField cxtripulacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabela1;
    private javax.swing.JTable tabelagb;
    // End of variables declaration//GEN-END:variables
}
